# Generated by Django 2.1.5 on 2019-01-14 20:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='otp',
            field=models.IntegerField(default=347723),
        ),
        migrations.AlterField(
            model_name='package',
            name='received_time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 1, 14, 20, 10, 46, 789035, tzinfo=utc)),
        ),
    ]
