# Generated by Django 2.1.5 on 2019-01-15 07:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0005_auto_20190115_0658'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='pile_no',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(7)]),
        ),
        migrations.AlterField(
            model_name='package',
            name='otp',
            field=models.IntegerField(default=324559),
        ),
    ]
