# Generated by Django 2.1.5 on 2019-01-15 08:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0006_auto_20190115_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='otp',
            field=models.IntegerField(default=504689),
        ),
        migrations.AlterField(
            model_name='package',
            name='pile_no',
            field=models.IntegerField(blank=True, default=1, validators=[django.core.validators.MaxValueValidator(7)]),
        ),
    ]
