# Generated by Django 2.1.5 on 2019-01-15 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0007_auto_20190115_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='order_id',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='package',
            name='otp',
            field=models.IntegerField(default=631381),
        ),
        migrations.AlterField(
            model_name='package',
            name='roll_no',
            field=models.CharField(max_length=30),
        ),
    ]
